_name_: "georgia"
name: "georgia"
database_path: '/mnt/data/lisa/physionet.org'
sampling_rate: 100  # 125
all_limb: false
segment_length: 1024  # 256  # 256 #  1024  # 2048  #   #  2048  # 2500
training_class: 'test'
label_names: ['AF', 'TAb', 'QAb', 'VPB', 'LAD', 'SA', 'LBBB', 'RBBB']  # ['IVAB', 'RBBB', 'LBBB', 'SB', 'AF', 'STach']
return_weights: false
negative_class: false