_name_: "ptbxl"
name: "ptbxl"
database_path: '/mnt/data/lisa/physionet.org/files/ptb-xl_clean/1.0.3'
sampling_rate: 100  # 125
all_limb: false
segment_length: 1024  # 256  #1024  # 256  # 256 #  1024  # 2048  #   #  2048  # 2500
training_class: 'test'
# label_names: ['AF', 'TAb', 'QAb', 'VPB', 'LAD', 'SA']
label_names: ['AF'] # AF, RBBB, SB, LBBB, NSR
#, ['AFIB', 'TAB_', 'QAb', 'VPB', 'LAD', 'SA']  # equivalence from https://physionet.org/content/ptb-xl/1.0.1/scp_statements.csv