lr: 3e-2 
optimizer: 'adam'
alpha: 0.5
seed: 0
ddim_init_steps: 200
n_steps: 50  # 300
threshold: 0.
init_std: 0.05
n_samples: 10
missingness: 1  # 3  # 50  # 20
missingness_type: 'lead' # 'lead'  #  'random_lead'  # 'bm'  # 'mnr'
downstream_classification: 'AF'

grad_steps_fn:
  conditions: 
    - condition: "i <= 20"
      return: 5 # 2
    - condition: "i >= n_steps - 10"
      return: 10
    - condition: "i % 20 == 0"
      return: 5 # 10
    - condition: "default"
      return: 5